### ISSUE TITLE
关于QIKT损失函数的疑惑

### ISSUE THREAD

**Issue by auakerman** [pykt-team/pykt-toolkit#110]
def train_one_step(self,data,process=True,return_all=False):
        outputs,data_new = self.predict_one_step(data,return_details=True,process=process)
        # all 
        loss_q_all = self.get_loss(outputs['y_question_all'],data_new['rshft'],data_new['sm'])
        loss_c_all = self.get_loss(outputs['y_concept_all'],data_new['rshft'],data_new['sm'])

作者你好，我看outputs中的y_question_all和y_concept_all好像是t时刻的预测值，而rshft是t+1时刻的真实值。 为什么要用这两个值做损失？请问是我哪里理解错误了吗

**Comment by Tong198-Hu** [comment]
Do you understand now, I also have some doubts, whether this is related to time series forecasting
