### ISSUE TITLE
关于dkt_forget模型

### ISSUE THREAD

**Issue by linchuanghong** [pykt-team/pykt-toolkit#127]
请问dkt_forget模型中，num_rgap、num_sgap、num_pcount三个参数代表什么呢？

**Comment by sonyawong** [comment]
> 请问dkt_forget模型中，num_rgap、num_sgap、num_pcount三个参数代表什么呢？

代表DKT-F论文中涉及的三个时间信息repeated time gap/sequence time gap/past exercise counts. 具体可以参考原论文https://dl.acm.org/doi/10.1145/3308558.3313565
