### ISSUE TITLE
您好，想问一下RKT的有关文件如何得到？

### ISSUE THREAD

**Issue by pokerme7777** [pykt-team/pykt-toolkit#134]
![image](https://github.com/pykt-team/pykt-toolkit/assets/80439452/5541b7bd-0f9f-475d-b72e-b497be76a547)
您好，想问一下这个地方rel是如何得到的？

**Comment by BojunZhan** [comment]
> ![image](https://user-images.githubusercontent.com/80439452/270952181-5541b7bd-0f9f-475d-b72e-b497be76a547.png) 您好，想问一下这个地方rel是如何得到的？

您好，谢谢您对我们工作的支持，rel代表着数据集处理后的pkl文件，这个pkl文件会在/pykt/datasets/data_loader.py 中生成

**Comment by BojunZhan** [comment]
> ![image](https://user-images.githubusercontent.com/80439452/270952181-5541b7bd-0f9f-475d-b72e-b497be76a547.png) 您好，想问一下这个地方rel是如何得到的？

您好，谢谢您对我们工作的支持，这个pkl文件会在/pykt/datasets/data_loader.py 中生成

**Comment by lightwindcy** [comment]
您好 ，这个 phi_array 是怎么得到的？我在运行时会产生错误信息FileNotFoundError: [Errno 2] No such file or directory: '../data/poj/phi_array_1_2_3_4.pkl'
，全局搜索 phi_array 也没有 找到它的相关信息
> > ![image](https://user-images.githubusercontent.com/80439452/270952181-5541b7bd-0f9f-475d-b72e-b497be76a547.png) 您好，想问一下这个地方rel是如何得到的？
> 
> 您好，谢谢您对我们工作的支持，这个pkl文件会在/pykt/datasets/data_loader.py 中生成

**Comment by henrywang777** [comment]
我按照作者的建议云兄了一遍,还是会报错：
FileNotFoundError: [Errno 2] No such file or directory: '../data/poj/phi_array_1_2_3_4.pkl'
请问解决了么

**Comment by Li-XYi** [comment]
你好，感谢对我们项目的关注。RKT文件的获取可以参考这个[issue回复](https://github.com/pykt-team/pykt-toolkit/issues/190#issuecomment-2257501994)。
