### ISSUE TITLE
Quick Start guide unclear

### ISSUE THREAD

**Issue by Xemorr** [pykt-team/pykt-toolkit#135]
Hi, I'm following the [quick start guide](https://pykt-toolkit.readthedocs.io/en/latest/quick_start.html), it is unclear how you are meant to access ``python data_preprocess.py [parameter]`` from the previous instructions on the page.

It would be great if this could be clarified

**Comment by BojunZhan** [comment]
Hi, you can go to the fold called examples, and then use python `data_preprocess.py [parameter]`

**Comment by BojunZhan** [comment]
> Xemorr

Hi, you can go to the fold called examples, and then use python `data_preprocess.py [parameter]`

**Comment by Xemorr** [comment]
This also hasn't been completed as the Quick Start Guide hasn't been updated to clarify this information
