### ISSUE TITLE
It is unclear how the files from the ednet dataset should be laid out when following the Quick Start Guide

### ISSUE THREAD

**Issue by Xemorr** [pykt-team/pykt-toolkit#137]
Similarly to my previous issue, it is not clear how I should lay out the files after downloading the various parts of the ednet dataset.
I currently have:
data/ednet/contents
data/ednet/KT1
data/ednet/KT2
data/ednet/KT3
data/ednet/KT4

I am getting a "ValueError, No objects to concatenate" when I run "python data_preprocess.py -d ednet", and am not enjoying reverse engineering the data processing scripts.

**Comment by Xemorr** [comment]
Through trial and error, I have discovered that the folder called "data" needs to be one level back from the working directory.

**Comment by demon2036** [comment]
Indeed,Quick Start Guide is RUBBISH

**Comment by Xemorr** [comment]
This hasn't been completed? 
![image](https://github.com/pykt-team/pykt-toolkit/assets/31805746/827613c2-a228-4334-bd78-edfa01cb589c)
Step 1 is still just as unclear as always, the relative position of the data folder needs to be made clear.
