### ISSUE TITLE
Clarification and Concerns Regarding Evaluation Code Files(eval.py and predict.py)

### ISSUE THREAD

**Issue by zyy-2001** [pykt-team/pykt-toolkit#140]
Hello, you've done a great job in knowledge tracking, but I have some questions about your open-source code. I noticed that there are two files in your code for evaluating models, eval.py and predict.py. As far as I understand, predict.py might not be using the fusion method, which means it could potentially lead to label leakage. Is my understanding correct, or could you please explain the difference between these two files?

**Comment by zyy-2001** [comment]
Does anyone know the reason? The child is very anxious.

**Comment by BojunZhan** [comment]
> Hello, you've done a great job in knowledge tracking, but I have some questions about your open-source code. I noticed that there are two files in your code for evaluating models, eval.py and predict.py. As far as I understand, predict.py might not be using the fusion method, which means it could potentially lead to label leakage. Is my understanding correct, or could you please explain the difference between these two files?

Hi,predict.py contains the fusion method. By using wandb_predict.py, it output one-by-one results, and for datasets with both topic and knowledge point ids, we additionally perform fustion predictions (pykt-toolkit/pykt/examples/wandb_predict.py line 78/ 86).wandb_eval is a scaled prediction method.For specific details you can read our paper：https://proceedings.neurips.cc/paper_files/paper/2022/file/75ca2b23d9794f02a92449af65a57556-Paper-Datasets_and_Benchmarks.pdf

**Comment by zyy-2001** [comment]
> > Hello, you've done a great job in knowledge tracking, but I have some questions about your open-source code. I noticed that there are two files in your code for evaluating models, eval.py and predict.py. As far as I understand, predict.py might not be using the fusion method, which means it could potentially lead to label leakage. Is my understanding correct, or could you please explain the difference between these two files?
> 
> Hi,predict.py contains the fusion method. By using wandb_predict.py, it output one-by-one results, and for datasets with both topic and knowledge point ids, we additionally perform fustion predictions (pykt-toolkit/pykt/examples/wandb_predict.py line 78/ 86).wandb_eval is a scaled prediction method.For specific details you can read our paper：https://proceedings.neurips.cc/paper_files/paper/2022/file/75ca2b23d9794f02a92449af65a57556-Paper-Datasets_and_Benchmarks.pdf

Thank you very much for your response to my issue. However, when I tried to reproduce the AUC results of the ASSIST2009 dataset using the DKT model, I noticed that the results are significantly higher than the reported result of 0.7541 in the paper. I used the "wandb_predict.py" file for this, so I suspect that this file may be causing label leakage. Below are the execution results:

{'testauc': 0.8266057062736684, 'testacc': 0.7720589422037154, 'window_testauc': 0.8277116048745647, 'window_testacc': 0.7724513292861629, 'oriaucconcepts': 0.8266057062736684, 'oriauclate_mean': 0.8266062165808796, 'oriauclate_vote': 0.8266057062736684, 'oriauclate_all': 0.8266057062736684, 'oriaccconcepts': 0.7720589422037154, 'oriacclate_mean': 0.7720428024984264, 'oriacclate_vote': 0.7720589422037154, 'oriacclate_all': 0.7720589422037154, 'windowaucconcepts': 0.8277116048745647, 'windowauclate_mean': 0.8277115601232611, 'windowauclate_vote': 0.8277116048745647, 'windowauclate_all': 0.8277116048745647, 'windowaccconcepts': 0.7724513292861629, 'windowacclate_mean': 0.7724513292861629, 'windowacclate_vote': 0.7724513292861629, 'windowacclate_all': 0.7724513292861629}

It is indeed possible that the "wandb_predict.py" file might be causing the issue, and label leakage should be investigated further to ensure the accuracy of the results.
