### ISSUE TITLE
It is unclear that where the dkt_que model file is 

### ISSUE THREAD

**Issue by xiangxin-oss** [pykt-team/pykt-toolkit#142]
The que_dkt_demo file of the example folder had import the  DKTQue method, but I don't find the relation file.
The raw code was " from pykt.models.dkt_que import DKTQue "

**Comment by BojunZhan** [comment]
Hello, thank you for your support of our work, about dkt_que, you can view and save in the dkt_improve branch.

**Comment by xiangxin-oss** [comment]
> Hello, thank you for your support of our work, about dkt_que, you can view and save in the dkt_improve branch.

Thank you ! I have found the file.
