### ISSUE TITLE
数据auc是选testauc还是validauc

### ISSUE THREAD

**Issue by MyGithub1234567890** [pykt-team/pykt-toolkit#144]
请问一下大佬，我们选用数据时候可以用验证集AUC吗 Epoch: 8, validauc: 0.7784, validacc: 0.7796, best epoch: 8, best auc: 0.7784, train loss: 10.460885047912598, emb_type: qid, model: iekt, save_dir:  还是必须用test呢？

**Comment by BojunZhan** [comment]
您好，感谢对我们工作的支持，我们在训练过程中选用最优模型采用的是validauc（会自动保存最优模型路径save_dir: XX）,最终，如果模型属于que_type_model,我们的test结果选用window_testauc。

**Comment by MyGithub1234567890** [comment]
> 您好，感谢对我们工作的支持，我们在训练过程中选用最优模型采用的是validauc（会自动保存最优模型路径save_dir: XX）,最终，如果模型属于que_type_model,我们的test结果选用window_testauc。
 是不是说 如果模型属于que_type_model，例如IEKT就选用window_testauc，其他模型就选普通的testauc？

**Comment by BojunZhan** [comment]
> > 您好，感谢对我们工作的支持，我们在训练过程中选用最优模型采用的是validauc（会自动保存最优模型路径save_dir: XX）,最终，如果模型属于que_type_model,我们的test结果选用window_testauc。
> > 是不是说 如果模型属于que_type_model，例如IEKT就选用window_testauc，其他模型就选普通的testauc？
对于非que_type_model,也就是KC level的模型，在测试的时候会存在标签泄漏问题，我们有对其进行fusion操作，一般来说我们会选择auclate_xx/windowauclate_xx这些结果。可以看看我们的论文哈：https://proceedings.neurips.cc/paper_files/paper/2022/hash/75ca2b23d9794f02a92449af65a57556-Abstract-Datasets_and_Benchmarks.html

**Comment by MyGithub1234567890** [comment]
还有个问题就是，test_dataset加载时，如果需要的数据window_testauc，那么代码在加载的时候，        elif model_name == "lpkt":
            test_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_file"]), at2idx, it2idx, data_config["input_type"], {-1})
            test_window_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_window_file"]), at2idx, it2idx, data_config["input_type"], {-1})
        elif model_name in que_type_models:
            test_dataset = KTQueDataset(os.path.join(data_config["dpath"], data_config["test_file_quelevel"]),
                            input_type=data_config["input_type"], folds=[-1],
                            concept_num=data_config['num_c'], max_concepts=data_config['max_concepts'])  是不是需要把data_config["test_file_quelevel"])改成data_config["test_window_file"]

**Comment by BojunZhan** [comment]
> 还有个问题就是，test_dataset加载时，如果需要的数据window_testauc，那么代码在加载的时候， elif model_name == "lpkt": test_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_file"]), at2idx, it2idx, data_config["input_type"], {-1}) test_window_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_window_file"]), at2idx, it2idx, data_config["input_type"], {-1}) elif model_name in que_type_models: test_dataset = KTQueDataset(os.path.join(data_config["dpath"], data_config["test_file_quelevel"]), input_type=data_config["input_type"], folds=[-1], concept_num=data_config['num_c'], max_concepts=data_config['max_concepts']) 是不是需要把data_config["test_file_quelevel"])改成data_config["test_window_file"]
我们在加载数据的时候，test_dataset和test_window_dataset都会加载，不需要手动进行修改，在预测的时候，在test_dataset and test_window_dataset 的预测结果都会一并给出。

**Comment by MyGithub1234567890** [comment]
> > 还有个问题就是，test_dataset加载时，如果需要的数据window_testauc，那么代码在加载的时候， elif model_name == "lpkt": test_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_file"]), at2idx, it2idx, data_config["input_type"], {-1}) test_window_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_window_file"]), at2idx, it2idx, data_config["input_type"], {-1}) elif model_name in que_type_models: test_dataset = KTQueDataset(os.path.join(data_config["dpath"], data_config["test_file_quelevel"]), input_type=data_config["input_type"], folds=[-1], concept_num=data_config['num_c'], max_concepts=data_config['max_concepts']) 是不是需要把data_config["test_file_quelevel"])改成data_config["test_window_file"]
> > 我们在加载数据的时候，test_dataset和test_window_dataset都会加载，不需要手动进行修改，在预测的时候，在test_dataset and test_window_dataset 的预测结果都会一并给出。

但是不改的话，每次跑window_testauc都是-1啊 像下面这样Epoch: 50, validauc: 0.9223, validacc: 0.868, best epoch: 46, best auc: 0.9223, train loss: 3.704118251800537, emb_type: qid, model: iekt, save_dir: saved_model\algebra2005_iekt_qid_saved_model_0.001_42_0_0_64_40_1_10_10_0.93_0_1
            testauc: -1, testacc: -1, window_testauc: -1, window_testacc: -1

**Comment by BojunZhan** [comment]
> > > 还有个问题就是，test_dataset加载时，如果需要的数据window_testauc，那么代码在加载的时候， elif model_name == "lpkt": test_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_file"]), at2idx, it2idx, data_config["input_type"], {-1}) test_window_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_window_file"]), at2idx, it2idx, data_config["input_type"], {-1}) elif model_name in que_type_models: test_dataset = KTQueDataset(os.path.join(data_config["dpath"], data_config["test_file_quelevel"]), input_type=data_config["input_type"], folds=[-1], concept_num=data_config['num_c'], max_concepts=data_config['max_concepts']) 是不是需要把data_config["test_file_quelevel"])改成data_config["test_window_file"]
> > > 我们在加载数据的时候，test_dataset和test_window_dataset都会加载，不需要手动进行修改，在预测的时候，在test_dataset and test_window_dataset 的预测结果都会一并给出。
> 
> 但是不改的话，每次跑window_testauc都是-1啊 像下面这样Epoch: 50, validauc: 0.9223, validacc: 0.868, best epoch: 46, best auc: 0.9223, train loss: 3.704118251800537, emb_type: qid, model: iekt, save_dir: saved_model\algebra2005_iekt_qid_saved_model_0.001_42_0_0_64_40_1_10_10_0.93_0_1 testauc: -1, testacc: -1, window_testauc: -1, window_testacc: -1

我们在训练的时候不会进行测试集的训练，我们的测试代码放在了wandb_predict.py中。

**Comment by BojunZhan** [comment]
您好，如果您还是有些地方不清楚，可以加我微信哈，方便点Zion0613 ---- 回复的原邮件 ***@***.***>发送日期2023年11月20日 19:27 ***@***.***> ***@***.***>***@***.***>主题Re: [pykt-team/pykt-toolkit] 数据auc是选testauc还是validauc (Issue #144)


还有个问题就是，test_dataset加载时，如果需要的数据window_testauc，那么代码在加载的时候， elif model_name == "lpkt": test_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_file"]), at2idx, it2idx, data_config["input_type"], {-1}) test_window_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_window_file"]), at2idx, it2idx, data_config["input_type"], {-1}) elif model_name in que_type_models: test_dataset = KTQueDataset(os.path.join(data_config["dpath"], data_config["test_file_quelevel"]), input_type=data_config["input_type"], folds=[-1], concept_num=data_config['num_c'], max_concepts=data_config['max_concepts']) 是不是需要把data_config["test_file_quelevel"])改成data_config["test_window_file"]
我们在加载数据的时候，test_dataset和test_window_dataset都会加载，不需要手动进行修改，在预测的时候，在test_dataset and test_window_dataset 的预测结果都会一并给出。


但是不改的话，每次跑window_testauc都是-1啊 像下面这样Epoch: 50, validauc: 0.9223, validacc: 0.868, best epoch: 46, best auc: 0.9223, train loss: 3.704118251800537, emb_type: qid, model: iekt, save_dir: saved_model\algebra2005_iekt_qid_saved_model_0.001_42_0_0_64_40_1_10_10_0.93_0_1
testauc: -1, testacc: -1, window_testauc: -1, window_testacc: -1

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pykt-team/pykt-toolkit/issues/144#issuecomment-1818870712",
"url": "https://github.com/pykt-team/pykt-toolkit/issues/144#issuecomment-1818870712",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MyGithub1234567890** [comment]
> > > > 还有个问题就是，test_dataset加载时，如果需要的数据window_testauc，那么代码在加载的时候， elif model_name == "lpkt": test_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_file"]), at2idx, it2idx, data_config["input_type"], {-1}) test_window_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_window_file"]), at2idx, it2idx, data_config["input_type"], {-1}) elif model_name in que_type_models: test_dataset = KTQueDataset(os.path.join(data_config["dpath"], data_config["test_file_quelevel"]), input_type=data_config["input_type"], folds=[-1], concept_num=data_config['num_c'], max_concepts=data_config['max_concepts']) 是不是需要把data_config["test_file_quelevel"])改成data_config["test_window_file"]
> > > > 我们在加载数据的时候，test_dataset和test_window_dataset都会加载，不需要手动进行修改，在预测的时候，在test_dataset and test_window_dataset 的预测结果都会一并给出。
> > 
> > 
> > 但是不改的话，每次跑window_testauc都是-1啊 像下面这样Epoch: 50, validauc: 0.9223, validacc: 0.868, best epoch: 46, best auc: 0.9223, train loss: 3.704118251800537, emb_type: qid, model: iekt, save_dir: saved_model\algebra2005_iekt_qid_saved_model_0.001_42_0_0_64_40_1_10_10_0.93_0_1 testauc: -1, testacc: -1, window_testauc: -1, window_testacc: -1
> 
> 我们在训练的时候不会进行测试集的训练，我们的测试代码放在了wandb_predict.py中。

所以就是先训练好模型，然后利用wandb_predict.py进行测试得到window_testauc，对吗？

**Comment by BojunZhan** [comment]
> > > > > 还有个问题就是，test_dataset加载时，如果需要的数据window_testauc，那么代码在加载的时候， elif model_name == "lpkt": test_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_file"]), at2idx, it2idx, data_config["input_type"], {-1}) test_window_dataset = LPKTDataset(os.path.join(data_config["dpath"], data_config["test_window_file"]), at2idx, it2idx, data_config["input_type"], {-1}) elif model_name in que_type_models: test_dataset = KTQueDataset(os.path.join(data_config["dpath"], data_config["test_file_quelevel"]), input_type=data_config["input_type"], folds=[-1], concept_num=data_config['num_c'], max_concepts=data_config['max_concepts']) 是不是需要把data_config["test_file_quelevel"])改成data_config["test_window_file"]
> > > > > 我们在加载数据的时候，test_dataset和test_window_dataset都会加载，不需要手动进行修改，在预测的时候，在test_dataset and test_window_dataset 的预测结果都会一并给出。
> > > 
> > > 
> > > 但是不改的话，每次跑window_testauc都是-1啊 像下面这样Epoch: 50, validauc: 0.9223, validacc: 0.868, best epoch: 46, best auc: 0.9223, train loss: 3.704118251800537, emb_type: qid, model: iekt, save_dir: saved_model\algebra2005_iekt_qid_saved_model_0.001_42_0_0_64_40_1_10_10_0.93_0_1 testauc: -1, testacc: -1, window_testauc: -1, window_testacc: -1
> > 
> > 
> > 我们在训练的时候不会进行测试集的训练，我们的测试代码放在了wandb_predict.py中。
> 
> 所以就是先训练好模型，然后利用wandb_predict.py进行测试得到window_testauc，对吗？

是的
