### ISSUE TITLE
data_preprocess script does not pass dataset_name to ednet_preprocess' read_data_from_csv

### ISSUE THREAD

**Issue by Xemorr** [pykt-team/pykt-toolkit#147]
![image](https://github.com/pykt-team/pykt-toolkit/assets/31805746/9f19952a-aef8-4e27-82a1-5c50945e5139)
There is only an entry for ednet5w passing the dataset_name in. Without passing in the dataset_name, start_i is never defined and it errors out

![image](https://github.com/pykt-team/pykt-toolkit/assets/31805746/1e81beb5-ca02-4f09-97f7-07482c51ac20)

**Comment by Xemorr** [comment]
@BojunZhan

**Comment by BojunZhan** [comment]
Ok, I understand your question. Sorry for the trouble to you. Due to our negligence, we did not consider the processing of ednet when adding the code processed by ednet5w. You can pass dataset_name when calling ednet_preprocess, and we'll change the code and push it up as soon as possible. Thank you!!

**Comment by Xemorr** [comment]
> Ok, I understand your question. Sorry for the trouble to you. Due to our negligence, we did not consider the processing of ednet when adding the code processed by ednet5w. You can pass dataset_name when calling ednet_preprocess, and we'll change the code and push it up as soon as possible. Thank you!!

Thank you! I get this issue ``ValueError: invalid literal for int() with base 10: ')'`` when running Ednet5W, do you know what's caused that?

**Comment by BojunZhan** [comment]
![IMG_4624](https://github.com/pykt-team/pykt-toolkit/assets/102374158/00cb2499-c3b2-4d55-b8b2-d6f396f79d85)
In def read_data in split_sequence, you can try to replace tmps[1] with tmps[-1]

**Comment by Xemorr** [comment]
Thank you so much for your help Zhan, one more question, what is the difference between ednet and ednet5w so I know whether I can use ednet5w for my usecase.

**Comment by badranX** [comment]
> > Ok, I understand your question. Sorry for the trouble to you. Due to our negligence, we did not consider the processing of ednet when adding the code processed by ednet5w. You can pass dataset_name when calling ednet_preprocess, and we'll change the code and push it up as soon as possible. Thank you!!
> 
> Thank you! I get this issue `ValueError: invalid literal for int() with base 10: ')'` when running Ednet5W, do you know what's caused that?

This problem originates from a bug in data preprocessing #145. But @BojunZhan solution is easier for a one case. I thought this project is dead :)

**Comment by BojunZhan** [comment]
> Thank you so much for your help Zhan, one more question, what is the difference between ednet and ednet5w so I know whether I can use ednet5w for my usecase.

The difference between ednet and ednet5w goes back to the amount of data, as the original ednet dataset was too large, we only sampled 5000 of these students initially, and as we followed up, we made an additional attempt to sample 50,000 students. In the usage scenario, you can choose ednet or ednet5w on your own as per your requirement.

**Comment by sonyawong** [comment]
> > > Ok, I understand your question. Sorry for the trouble to you. Due to our negligence, we did not consider the processing of ednet when adding the code processed by ednet5w. You can pass dataset_name when calling ednet_preprocess, and we'll change the code and push it up as soon as possible. Thank you!!
> > 
> > 
> > Thank you! I get this issue `ValueError: invalid literal for int() with base 10: ')'` when running Ednet5W, do you know what's caused that?
> 
> This problem originates from a bug in data preprocessing #145. But @BojunZhan solution is easier for a one case. I thought this project is dead :)

Hii, thank you for pointing out the issue caused by pandas versions when conducting data preprocessing and providing appropriate solution.  We have fixed the issues. If you have any other questions about our repo, please feel free to contact us. Thx!!

**Comment by MyGithub1234567890** [comment]
> > > > 好的，我明白你的问题。很抱歉给您带来麻烦。由于我们的疏忽，我们在添加ednet5w处理的代码时没有考虑ednet的处理。调用ednet_preprocess时可以传递dataset_name，我们会尽快更改代码并推送。谢谢！！
> > > 
> > > 
> > > 谢谢！我在运行 Ednet5W 时遇到这个问题，你知道是什么原因造成的吗？`ValueError: invalid literal for int() with base 10: ')'`
> > 
> > 
> > 此问题源于数据预处理 #145 中的错误。但对于一个案例来说，解决方案更容易。我以为这个项目已经死了:)
> 
> 嗨，感谢您在进行数据预处理并提供适当的解决方案时指出 pandas 版本引起的问题。我们已经解决了这些问题。如果您对我们的回购有任何其他疑问，请随时与我们联系。感谢！！

想问一下如果要使用ednet5w 在dataprocess文件中，路径是 "ednet5w": "../data/ednet/",还是"../data/ednet5w/"呢？

**Comment by BojunZhan** [comment]
> > > > > 好的，我明白你的问题。很抱歉给您带来麻烦。由于我们的疏忽，我们在添加ednet5w处理的代码时没有考虑ednet的处理。调用ednet_preprocess时可以传递dataset_name，我们会尽快更改代码并推送。谢谢！！
> > > > 
> > > > 
> > > > 谢谢！我在运行 Ednet5W 时遇到这个问题，你知道是什么原因造成的吗？`ValueError: invalid literal for int() with base 10: ')'`
> > > 
> > > 
> > > 此问题源于数据预处理 #145 中的错误。但对于一个案例来说，解决方案更容易。我以为这个项目已经死了:)
> > 
> > 
> > 嗨，感谢您在进行数据预处理并提供适当的解决方案时指出 pandas 版本引起的问题。我们已经解决了这些问题。如果您对我们的回购有任何其他疑问，请随时与我们联系。感谢！！
> 
> 想问一下如果要使用ednet5w 在dataprocess文件中，路径是 "ednet5w": "../data/ednet/",还是"../data/ednet5w/"呢？
路径设置成"ednet5w":"../data/ednet/"，因为我们sample的原始数据集还是在“../data/ednet”之中

**Comment by BojunZhan** [comment]
> MyGithub1234567890



> > > > > 好的，我明白你的问题。很抱歉给您带来麻烦。由于我们的疏忽，我们在添加ednet5w处理的代码时没有考虑ednet的处理。调用ednet_preprocess时可以传递dataset_name，我们会尽快更改代码并推送。谢谢！！
> > > > 
> > > > 
> > > > 谢谢！我在运行 Ednet5W 时遇到这个问题，你知道是什么原因造成的吗？`ValueError: invalid literal for int() with base 10: ')'`
> > > 
> > > 
> > > 此问题源于数据预处理 #145 中的错误。但对于一个案例来说，解决方案更容易。我以为这个项目已经死了:)
> > 
> > 
> > 嗨，感谢您在进行数据预处理并提供适当的解决方案时指出 pandas 版本引起的问题。我们已经解决了这些问题。如果您对我们的回购有任何其他疑问，请随时与我们联系。感谢！！
> 
> 想问一下如果要使用ednet5w 在dataprocess文件中，路径是 "ednet5w": "../data/ednet/",还是"../data/ednet5w/"呢？

路径是：“ednet5w":"../data/ednet"
