### ISSUE TITLE
小白不懂就问：如何进行数据预处理操作

### ISSUE THREAD

**Issue by xiangxin-oss** [pykt-team/pykt-toolkit#156]
求助大佬~
我是把整个包以zip的方式下载然后作为project在pycharm中打开。我按照pykt的quick start中的提示，先将路径定位到我电脑中这个包里面examples文件夹的位置，然后运行python data_preprocess.py --dataset_name=assist2009， 就会出现下述报错：
![image](https://github.com/pykt-team/pykt-toolkit/assets/81347491/4d4b3b2f-337f-4b4a-ba72-306824fcbd3f)

请问我要跑其他公共数据是都需要自行先把相关的数据集下载好吗~

我尝试从网上下载提到的这份assist2009的数据，但是又出现的另一个错：
![image](https://github.com/pykt-team/pykt-toolkit/assets/81347491/6d8654b0-7cde-4ded-ac1f-dd7a54abae6b)

我下载的数据是这样的：
![image](https://github.com/pykt-team/pykt-toolkit/assets/81347491/b8feb2b0-5a61-4ee6-843b-342817a2aa73)

我从网上找上述错误的解决方法，我将utf-8 改成 gbk 又报了其他的错：
![image](https://github.com/pykt-team/pykt-toolkit/assets/81347491/199e023b-78e3-417e-8209-e8998d454f27)
我看网上解决方案都是加个float，但是加了这个又会报错，然后有评论说编码转成utf-8.
已经彻底晕了，求助热心的大佬！！！

**Comment by Yumo216** [comment]
请问你怎么解决的
