### ISSUE TITLE
评估名称含义

### ISSUE THREAD

**Issue by zncj2fdx** [pykt-team/pykt-toolkit#163]
{'testauc': 0.7943788209673547, 'testacc': 0.7475768932540708, 'window_testauc': 0.7685039082171022, 'window_testacc': 0.7318665377176016, 'oriaucconcepts': 0.7110754888163919, 'oriauclate_mean': 0.7255579265298452, 'oriauclate_vote': 0.7230106911026343, 'oriauclate_all': 0.7220473461552641, 'oriaucearly_preds': 0.7217815333611654, 'oriaccconcepts': 0.70147125542809, 'oriacclate_mean': 0.707122899682321, 'oriacclate_vote': 0.7085773337926283, 'oriacclate_all': 0.7044436789528075, 'oriaccearly_preds': 0.7070846251004708, 'windowaucconcepts': 0.7092364949499445, 'windowauclate_mean': 0.7249410146047867, 'windowauclate_vote': 0.7223734350511717, 'windowauclate_all': 0.7206904584945073, 'windowaucearly_preds': 0.7194530945391587, 'windowaccconcepts': 0.7006560873921334, 'windowacclate_mean': 0.7055061285272443, 'windowacclate_vote': 0.7080644545419833, 'windowacclate_all': 0.7035396540532285, 'windowaccearly_preds': 0.7055252205124288}

您好，可以解释以下每一个评估名称的代表的含义吗？

**Comment by Li-XYi** [comment]
感谢您对我们项目的关注和支持，关于评估名称的含义，可以参考这个[issue](https://github.com/pykt-team/pykt-toolkit/issues/120)。
