### ISSUE TITLE
Could you please provide guidance on obtaining the correct datasets?

### ISSUE THREAD

**Issue by WinterGan** [pykt-team/pykt-toolkit#168]
Thank you for your outstanding work on PyKT. I've been using it, but I'm facing problems with certain datasets – either they don't run or produce AUC values exceeding your reported results. I suspect it's a data download issue on my end. Could you guide me on obtaining the correct datasets?

**Comment by lycyhrc** [comment]
Pykt benchmark provides a data set of a download link, you can find and download here he  (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html), The processing of data set file in this (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess), if you need to add other data set benchmark, You need to add the processing code for the dataset under the /preprocess directory. @WinterGan

**Comment by WinterGan** [comment]
> Pykt benchmark provides a data set of a download link, you can find and download here he (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html), The processing of data set file in this (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess), if you need to add other data set benchmark, You need to add the processing code for the dataset under the /preprocess directory. @WinterGan

I appreciate your help. Previously, I downloaded datasets from the provided link (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html) and processed them using the data processing tools (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess). Unfortunately, I encountered issues. Could you kindly provide direct access to the datasets?

**Comment by lycyhrc** [comment]
> > Pykt benchmark provides a data set of a download link, you can find and download here he (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html), The processing of data set file in this (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess), if you need to add other data set benchmark, You need to add the processing code for the dataset under the /preprocess directory. @WinterGan
> 
> I appreciate your help. Previously, I downloaded datasets from the provided link (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html) and processed them using the data processing tools (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess). Unfortunately, I encountered issues. Could you kindly provide direct access to the datasets?


Can you provide more details on which dataset you have this problem?

**Comment by WinterGan** [comment]
> > > Pykt benchmark provides a data set of a download link, you can find and download here he (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html), The processing of data set file in this (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess), if you need to add other data set benchmark, You need to add the processing code for the dataset under the /preprocess directory. @WinterGan
> > 
> > 
> > I appreciate your help. Previously, I downloaded datasets from the provided link (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html) and processed them using the data processing tools (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess). Unfortunately, I encountered issues. Could you kindly provide direct access to the datasets?
> 
> Can you provide more details on which dataset you have this problem?

Hello,I obtained the datasets using the links provided on the website. I encountered issues with missing files for the assist2009 and statics2011 datasets. While algebra2005 and poj datasets run successfully, the AUC values differ from those reported in the paper. To address these problems, could you please provide direct access to the files for these four datasets? I genuinely appreciate your contributions.

**Comment by lycyhrc** [comment]
> > > > Pykt benchmark provides a data set of a download link, you can find and download here he (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html), The processing of data set file in this (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess), if you need to add other data set benchmark, You need to add the processing code for the dataset under the /preprocess directory. @WinterGan
> > > 
> > > 
> > > I appreciate your help. Previously, I downloaded datasets from the provided link (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html) and processed them using the data processing tools (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess). Unfortunately, I encountered issues. Could you kindly provide direct access to the datasets?
> > 
> > 
> > Can you provide more details on which dataset you have this problem?
> 
> Hello,I obtained the datasets using the links provided on the website. I encountered issues with missing files for the assist2009 and statics2011 datasets. While algebra2005 and poj datasets run successfully, the AUC values differ from those reported in the paper. To address these problems, could you please provide direct access to the files for these four datasets? I genuinely appreciate your contributions.



These datasets you need can be downloaded from here (https://drive.google.com/drive/folders/1CqYkJWno9oh0kPAt3eHRWowFR6BqeQsS?usp=drive_link), if you have any other question, please continue to reply. If your issue has been resolved, please close this issue. thanks.

**Comment by WinterGan** [comment]
> > > > > Pykt benchmark provides a data set of a download link, you can find and download here he (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html), The processing of data set file in this (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess), if you need to add other data set benchmark, You need to add the processing code for the dataset under the /preprocess directory. @WinterGan
> > > > 
> > > > 
> > > > I appreciate your help. Previously, I downloaded datasets from the provided link (https://pykt-toolkit.readthedocs.io/en/latest/datasets.html) and processed them using the data processing tools (https://github.com/pykt-team/pykt-toolkit/tree/main/pykt/preprocess). Unfortunately, I encountered issues. Could you kindly provide direct access to the datasets?
> > > 
> > > 
> > > Can you provide more details on which dataset you have this problem?
> > 
> > 
> > Hello,I obtained the datasets using the links provided on the website. I encountered issues with missing files for the assist2009 and statics2011 datasets. While algebra2005 and poj datasets run successfully, the AUC values differ from those reported in the paper. To address these problems, could you please provide direct access to the files for these four datasets? I genuinely appreciate your contributions.
> 
> These datasets you need can be downloaded from here (https://drive.google.com/drive/folders/1CqYkJWno9oh0kPAt3eHRWowFR6BqeQsS?usp=drive_link), if you have any other question, please continue to reply. If your issue has been resolved, please close this issue. thanks.

May I inquire if my access request can be approved?
