### ISSUE TITLE
AT-DKT 运行结果比论文结果高了10%

### ISSUE THREAD

**Issue by Lindseysd** [pykt-team/pykt-toolkit#185]
您好，感谢您团队的贡献！
论文中AT-DKT在algebra2005数据集上的结果是0.8246，但是我的运行结果是0.9224，请问我是哪里做错了吗。
![屏幕截图 2024-04-19 165128](https://github.com/pykt-team/pykt-toolkit/assets/167517862/5f016c28-f1ba-458d-bf7d-6bd34ee92377)
![image](https://github.com/pykt-team/pykt-toolkit/assets/167517862/06e2e4ec-9790-4f5a-a730-e6a2ab76425e)

**Comment by LeavesLi1015** [comment]
我也有这样的疑惑

**Comment by LeavesLi1015** [comment]
在之前的一个issue中，有人提到了这个问题https://github.com/pykt-team/pykt-toolkit/issues/144
在使用KC-level的模型时，应该参考"window{metrics}late"这样的指标，其他指标会涉及数据泄露问题

**Comment by Liu-lqq** [comment]
0.9224是验证集的效果、且是知识点粒度的效果（存在标签泄漏的问题，测试question粒度比较耗时，因此这里用的是知识点粒度的来指导训练）；
而论文中的是题目粒度的效果。
知识点粒度和题目粒度更细的差异可以参考论文:
pyKT: A Python Library to Benchmark Deep Learning based Knowledge Tracing Models
