### ISSUE TITLE
关于RKT中找不到文件的问题

### ISSUE THREAD

**Issue by henrywang777** [pykt-team/pykt-toolkit#190]
感谢您的贡献，但是我在训练RKT时，报错：
FileNotFoundError: [Errno 2] No such file or directory: '../data/assist2009\\phi_array_1_2_3_4.pkl'
请问怎么解决?
我运行了一遍pykt\datasets\data_loader.py，还是没有此文件。

**Comment by Yumo216** [comment]
同问，请问您解决了吗。怎么作者也不回复呀

**Comment by henrywang777** [comment]
不好意思，我也没有解决



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 姚羽默 ***@***.***&gt;
发送时间: 2024年7月29日 21:25
收件人: pykt-team/pykt-toolkit ***@***.***&gt;
抄送: henrywang777 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pykt-team/pykt-toolkit] 关于RKT中找不到文件的问题 (Issue #190)





 
同问，请问您解决了吗。怎么作者也不回复呀

**Comment by Yumo216** [comment]
请问您现在还从事知识追踪的研究吗。您有其他方式复现rkt的吗

**Comment by henrywang777** [comment]
在研究的哈，RKT原论文中有实现代码链接，我现在身边没有电脑，不好意思，但是原论文给出的代码我看了也没有完全实现。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 姚羽默 ***@***.***&gt;
发送时间: 2024年7月30日 00:06
收件人: pykt-team/pykt-toolkit ***@***.***&gt;
抄送: henrywang777 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pykt-team/pykt-toolkit] 关于RKT中找不到文件的问题 (Issue #190)





 
请问您现在还从事知识追踪的研究吗。您有其他方式复现rkt的吗

**Comment by Yumo216** [comment]
好的谢啦，祝顺

**Comment by lycyhrc** [comment]
> 感谢您的贡献，但是我在训练RKT时，报错： FileNotFoundError: [Errno 2] No such file or directory: '../data/assist2009\phi_array_1_2_3_4.pkl' 请问怎么解决? 我运行了一遍pykt\datasets\data_loader.py，还是没有此文件。

@henrywang777  @Yumo216  
I’m very sorry for the late reply. Because the `pkl` files for the RKT model need to be pre-generated and are large, we weren’t able to upload the corresponding generated files to the project. You can download the files from [Google Drive -RKT .pkl files](https://drive.google.com/drive/folders/1JDQJJP_j0sRHWx3YtfURapW4tg861Djp?usp=sharing) and place them in the appropriate folder. If you have any further questions or concerns, please don’t hesitate to reply to this issue.

**Comment by lycyhrc** [comment]
> 非常感谢您提供的数据集，但是在RKT中的POJ数据集似乎没有找到。您在docs中提供的POJ下载地址[POJ](https://drive.google.com/drive/folders/1LRljqWfODwTYRMPw6wEJ_mMt1KZ4xBDk)，也已经失效，请问是否能再次提供一份POJ的数据集，感谢
> 
> <img alt="Image" width="259" height="208" src="https://private-user-images.githubusercontent.com/77867386/467958472-95d88bc5-e8a9-4f3d-8005-eef850a9ca6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI4OTI2ODEsIm5iZiI6MTc1Mjg5MjM4MSwicGF0aCI6Ii83Nzg2NzM4Ni80Njc5NTg0NzItOTVkODhiYzUtZThhOS00ZjNkLTgwMDUtZWVmODUwYTljYTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE5VDAyMzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNjQyYjBkMTc0NGY3ZmQ2ZmI3MzI0NDg2ZjZkZjc3YzYwY2I3ZWNlZjhlYmQ0NmNlYjdmNGU5ZDBkYmMyNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AHQfo2VMt_YeKpjx5pO1BhU2mDs6EuzjHSnIIuFMK18">

https://drive.google.com/drive/folders/1XiyyHkaqJiwnDDvc0kT5TZLMEIClKiuV?usp=sharing 感谢关注, poj的数据集可以在这里下载
