### ISSUE TITLE
LPKT模型中gamma_f每个维度的含义

### ISSUE THREAD

**Issue by Mars160** [pykt-team/pykt-toolkit#194]
Hi,非常感谢贵团队杰出的工作，我们团队目前希望通过LPKT模型获取学生的对于知识点的遗忘因子，通过学习和源码阅读推测可能是pykt/models/lpkt.py中的gamma_f

后面发现该参数包含三个维度，据分析第二维度似乎是概念数，第三维度是网络隐藏层数？想请教第一各维度有什么具体含义
如何将gamma_f与具体的每个学生联系起来？

谢谢！

我们团队修改的代码在[Personalized-Learning-Laboratory/pykt-toolkit)](https://github.com/Personalized-Learning-Laboratory/pykt-toolkit/blob/main/pykt)

非常感谢

**Comment by sonyawong** [comment]
> Hi,非常感谢贵团队杰出的工作，我们团队目前希望通过LPKT模型获取学生的对于知识点的遗忘因子，通过学习和源码阅读推测可能是pykt/models/lpkt.py中的gamma_f
> 
> 后面发现该参数包含三个维度，据分析第二维度似乎是概念数，第三维度是网络隐藏层数？想请教第一各维度有什么具体含义 如何将gamma_f与具体的每个学生联系起来？
> 
> 谢谢！
> 
> 我们团队修改的代码在[Personalized-Learning-Laboratory/pykt-toolkit)](https://github.com/Personalized-Learning-Laboratory/pykt-toolkit/blob/main/pykt)
> 
> 非常感谢

hi,感谢贵组对我们工作的关注, gamma_f对应的是原论文eq.(6)的forgetting gate ,维度为[batch_size, num_c, dim_k], 所以我的理解是第一维度每一个矩阵就代表各个学生在各个知识点的遗忘情况, 谢谢~
