### ISSUE TITLE
SparseKT关于sparse_ratio的疑惑

### ISSUE THREAD

**Issue by YIUYA** [pykt-team/pykt-toolkit#199]
您好，我有一个关于sparse_ratio这个参数的疑惑。 根据分享的SparseKT超参数值，emb_type 是 qid_sparseattn, 然而代码里面如果是这个类别，根本就用不到sparse_ratio的值。 但是在超参文件中却有不同的sparse_ratio的值， 请问这个值会对预测效果有不同的影响吗？

**Comment by lycyhrc** [comment]
> 您好，我有一个关于sparse_ratio这个参数的疑惑。 根据分享的SparseKT超参数值，emb_type 是 qid_sparseattn, 然而代码里面如果是这个类别，根本就用不到sparse_ratio的值。 但是在超参文件中却有不同的sparse_ratio的值， 请问这个值会对预测效果有不同的影响吗？

您好，这里的默认emb_type 应该是`qid`, sparse_ratio作为一个超参数。我们对默认emb_type值进行了修改更新，感谢您的关注。

**Comment by CVEngineer66** [comment]
你好，我想问一下这个emb_type是什么含义？因为刚接触这个项目，我始终都没有找到对这个参数的解释。感谢解答！

**Comment by lycyhrc** [comment]
> 你好，我想问一下这个emb_type是什么含义？因为刚接触这个项目，我始终都没有找到对这个参数的解释。感谢解答！

emb_type可以在train和yaml文件进行不同的设置，方便对模型一起进行消融实验
