### ISSUE TITLE
The recent models show 'None'

### ISSUE THREAD

**Issue by puding26** [pykt-team/pykt-toolkit#209]
Hi, I am reproducing the pykt-toolkit baselines. When I am running into recent models, e.g. stablekt, it shows 'None' in the main training files. Can you help me to solve the issue?
![screen](https://github.com/user-attachments/assets/e939a2da-f489-419a-8c83-79580e8f35a1)
Thanks a lot.

**Comment by Li-XYi** [comment]
Hi, thank you for reaching out! To resolve this issue, please try the following steps:
1. Re-clone the project repository to ensure all files are up-to-date.
2. In the project’s root directory, run `pip install -e .` to complete the project installation.
3. Navigate to the `pykt-toolkit/examples` directory.
4. Execute the command `python wandb_stablekt_train.py` to start the training process for stablekt.

**Comment by puding26** [comment]
Thank you. My problem has been resolved.
