### ISSUE TITLE
About run environment

### ISSUE THREAD

**Issue by coder-zc** [pykt-team/pykt-toolkit#53]
Excuse me, can the model run only in the GPU environment that supports cuda?

**Comment by meta-tabchen** [comment]
Hi~thank you for your interest in our work. Yes, now we only support GPU machines, we will support CPU machines in the future. 

And you can try to modify `pykt/datasets/data_loader.py` where we use `from torch.cuda import FloatTensor, LongTensor` to set the default machine to GPU, maybe you can change this line to support CPU.

**Comment by coder-zc** [comment]
Thank you for your reply！i tried to change `from torch.cuda import FloatTensor, LongTensor` into `from torch import FloatTensor, LongTensor`, which can run in the CPU.

**Comment by meta-tabchen** [comment]
Thank you for your results, we will update this to a future version.

**Comment by meta-tabchen** [comment]
> Hello! i want to konw why generate window_sequences when testing. Could you briefly describe the sequence_window of how and why to do this，which generate a large number of sequences.

Hello ! [here](https://github.com/pykt-team/pykt-toolkit/discussions/48#discussion-4409822) has some discussions, if that does not answer your question, please let us know.
