### ISSUE TITLE
multi-skill exercises?

### ISSUE THREAD

**Issue by wangshu1331** [pykt-team/pykt-toolkit#74]
Hi, can I use the multi-skill exercises of myself dataset?
For example：i have a exercises list $E={e_1,e_2,...,e_n}$，$e_ i$ have skill ${s_j，s_k，s_h}$ (j!=k&&k!=h&&j!=h)
whether support my dataset from other source(sush as :[codeforces.com](https://codeforces.com/),[luogu.com.cn](https://www.luogu.com.cn/))?

**Comment by sonyawong** [comment]
> Hi, can I use the multi-skill exercises of myself dataset? For example：i have a exercises list $E={e_1,e_2,...,e_n}$，$e_ i$ have skill ${s_j，s_k，s_h}$ (j!=k&&k!=h&&j!=h) whether support my dataset from other source(sush as :[codeforces.com](https://codeforces.com/),[luogu.com.cn](https://www.luogu.com.cn/))?

Hi, thank you for your attention to our work. If you want to add a new dataset, you can perform a new data preprocess file into ./pykt/preprocess/. For the exercise with multiple skills, you may separate the skills with the underline "_". In our setting to generate training/valid/testing data, a multi-skill exercise is repeated multiple times, one for each skill. More details can be seen at https://pykt-toolkit.readthedocs.io/en/latest/contribute.html.

**Comment by wangshu1331** [comment]
> 
Thank you for your reply, I will read the relevant documents carefully and try to solve the problem I encountered. Your project has helped me tremendously in my research, thank you very much for open source!
