### ISSUE TITLE
module 'pykt' or package 'pykt'?

### ISSUE THREAD

**Issue by wangshu1331** [pykt-team/pykt-toolkit#79]
Hi, your pykt is a very nice project. But I got the following traceback on my machine :
``` bash
  File "**/pykt-toolkit/examples/wandb_train.py", line 71, in main
    (train_loader, valid_loader) = init_dataset4train(dataset_name, model_name, data_config, fold, batch_size)
ValueError: too many values to unpack (expected 2)
```

after my troubleshooted,I find  we have a package named `pykt`,and a module named `pykt` too. The paths for both of them are as follows：

+  module  `pykt `: **/pykt-toolkit/pykt
+ package `pykt` ：**/envs/pykt/lib/python3.7/site-packages/pykt

According to the description of the `Modules` section of the python website (https://docs.python.org/3/tutorial/modules.html)，`from-import` will choise  package  `pykt ` frist.

So, have you encountered the same problem, or can you give me some suggestions to solve it? 
thank you very much!

**Comment by meta-tabchen** [comment]
Thanks for your attention to our project. pyKT is a project, you can try cloning the source codes, then go to the directory you cloned, and use the `pip install -e .` command to install pyKT package.  Then the package and module will keep the same. For the problem, can you provide more details, such as the command you run?

**Comment by wangshu1331** [comment]
> Thanks for your attention to our project. pyKT is a project, you can try cloning the source codes, then go to the directory you cloned, and use the `pip install -e .` command to install pyKT package. Then the package and module will keep the same. For the problem, can you provide more details, such as the command you run?

thank you very much!，i use `pip install -e .` command,and use code `sys.path.append('**/pykt-toolkit') `solved the  problem, The project can be operated normally now. I use only default command of 

`CUDA_VISIBLE_DEVICES=2 python wandb_sakt_train.py --dataset_name=assist2015 --use_wandb=0 --add_uuid=0 --num_attn_heads=2 `
