### ISSUE TITLE
How to evaluate with question level? 

### ISSUE THREAD

**Issue by venzino-han** [pykt-team/pykt-toolkit#94]
In the pykt paper, it seems to evaluate model with KC level. 

How can we evalutate model in question level?

It is different with early fusion because, in the peper, DKT/GKT didn't evaluate with early fusion setting.

Do you have any plan to add question level evaluation metrics?

**Comment by meta-tabchen** [comment]
Hi, pyKT already has question-level evaluation metrics you can see our doc [here](https://pykt-toolkit.readthedocs.io/en/latest/quick_start.html#evaluating-your-model).

In our paper, we use the question level to evaluate different models (section "3.3.1 Real-world Prediction Scenarios"), the KC level result just to show the label leakage problems (Table 2).

**Comment by venzino-han** [comment]
@meta-tabchen Thanks for your kind reply! Forgive my misunderstanding.
