### ISSUE TITLE
GKT training time 

### ISSUE THREAD

**Issue by venzino-han** [pykt-team/pykt-toolkit#95]
How long does it takes for GKT training? 

In my case it takes more than 2hours per epoch in junyi2015 dataset. 

Is it normal?

Sharing other datasets training time of GKT might be helpful! 

Thank you!

**Comment by meta-tabchen** [comment]
The training time of a machine learning model can be influenced by several factors, for example, the computational resources available (such as GPU type and the number of tasks running on one GPU) and the choice of hyperparameters. For your convenience, we have included the average training time (hours) with standard deviation for all models and datasets using the NVIDIA RTX A5000 GPU as a reference.

| Model | Assist2009 | Algebra2005 | Bridge2006  | NIPS34     | Statics2011 | Assist2015  | POJ         |
| ----- | ---------- | ----------- | ----------- | ---------- | ----------- | ----------- | ----------- |
| DKT   | 0.03±0.02  | 0.10±0.07   | 0.68±0.46   | 0.10±0.13  | 0.06±0.04   | 0.30±0.27   | 0.51±0.46   |
| DKT+  | 0.01±0.01  | 0.04±0.03   | 0.11±0.13   | 0.02±0.02  | 0.01±0.00   | 0.04±0.06   | 0.17±0.18   |
| DKT-F | -          | 0.29±0.15   | 1.33±0.60   | 0.12±0.07  | 0.06±0.04   | -           | 0.28±0.21   |
| KQN   | 0.02±0.01  | 0.10±0.06   | 0.11±0.06   | 0.12±0.09  | 0.02±0.01   | 0.23±0.19   | 0.23±0.31   |
| DKVMN | 0.20±0.11  | 0.51±0.43   | 0.35±0.23   | 0.21±0.07  | 0.06±0.03   | 1.67±1.31   | 1.79±2.09   |
| ATKT  | 0.08±0.05  | 0.10±0.06   | 0.20±0.07   | 0.21±0.08  | 0.03±0.01   | 0.37±0.39   | 0.42±0.42   |
| GKT   | 7.07±5.52  | 10.92±7.08  | 27.22±15.67 | 13.62±9.67 | 5.67±2.91   | 16.39±11.90 | 31.40±21.48 |
| SAKT  | 0.04±0.02  | 0.12±0.09   | 0.07±0.09   | 0.10±0.09  | 0.01±0.01   | 0.18±0.17   | 0.23±0.28   |
| SAINT | 0.03±0.02  | 0.06±0.07   | 0.16±0.17   | 0.39±0.44  | 0.04±0.03   | 0.30±0.24   | 0.10±0.07   |
| AKT   | 0.08±0.07  | 0.45±0.50   | 0.33±0.31   | 0.17±0.11  | 0.03±0.02   | 0.39±0.23   | 0.32±0.21   |

**Comment by venzino-han** [comment]
@meta-tabchen  thanks! It helps a lot.
